services:
  postgres:
    image: postgres:16-alpine
    container_name: quizforge-postgres
    environment:
      POSTGRES_DB: quizforge
      POSTGRES_USER: quizforge
      POSTGRES_PASSWORD: quizforge123
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/data/postgres
    restart: unless-stopped
    networks:
      - quizforge-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U quizforge -d quizforge" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quizforge-srv
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quizforge
      SPRING_DATASOURCE_USERNAME: quizforge
      SPRING_DATASOURCE_PASSWORD: quizforge123
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    networks:
      - quizforge-network

volumes:
  postgres-data:

networks:
  quizforge-network:
    driver: bridge