spring:
  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
